from pathlib import Path

from ..models.output_format import OutputFormat

DEFAULT_OUTPUT_PATH: Path = Path.home() / "Downloads"
DEFAULT_OUTPUT_FORMAT: OutputFormat = OutputFormat.PDF
DEFAULT_QUALITY: int = 75
DEFAULT_OPTIMIZE: bool = False
DEFAULT_DATA_SAVER: bool = False

DEFAULT_RESOLVE_WORKERS: int = 2
DEFAULT_DOWNLOAD_WORKERS: int = 2
DEFAULT_MERGE_WORKERS: int = 2
DEFAULT_UPLOAD_WORKERS: int = 2

DEFAULT_PROVIDER_RATE_LIMIT: int = 10
DEFAULT_DOWNLOAD_RATE_LIMIT: int = 20
DEFAULT_QUEUE_SIZE: int = 2

DEFAULT_JOB_EXPIRY_SECONDS: int = 300
